version: "3.7"
services:
  app:
    build:
      args:
        user: marky
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: marckx
    container_name: affiliate-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www

  nginx:
    image: nginx:alpine
    container_name: affiliate-nginx
    restart: unless-stopped
    ports:
      - 8002:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/


